ProyectoWeb/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls, name='Admin'),

    path('conocenos/', include('conocenos.urls')),

    path('blog/', include('blog.urls')),

    path('contacto/', include('contacto.urls')),

    path('estudiante/', include('estudiante.urls')),

    path('registrarse/', include('registrarse.urls')),

    path('asignaciondecursos/', include('asignaciondecursos.urls')),

    path('asignacion/', include('asignacion.urls')),

    path('docente/', include('docente.urls')),

    path('administrativo/', include('administrativo.urls')),
    
    path('', include('ProyectoWebApp.urls')),

    
    
]

asignaciondecursos/urls.py
from django.urls import path

from .import views 

app_name="asignaciondecursos"

urlpatterns = [
    
    path("agregar/<int:curso_id>/", views.agregar_curso, name="agregar"),
    path("eliminar/<int:curso_id>/", views.eliminar_curso, name="eliminar"),
    path("restar/<int:curso_id>/", views.restar_curso, name="restar"),
    path("limpiar/", views.limpiar_asignaciondecursos, name="limpiar"),
    
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('',views.blog, name='Blog'),
    path('categoria/<int:categoria_id>/', views.categoria, name="categoria")
]

estudiante/urls.py
from django.urls import path

from .import views 

urlpatterns = [
    
    path('',views.estudiante, name='Estudiante'),
    

    
]

estudiante/models.py
from django.db import models

# Create your models here.

class CategoriaCur(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name="categoriaCur"
        verbose_name_plural="categoriasCur"

    def __str__(self):
        return self.nombre
    

class Curso(models.Model):
    nombre=models.CharField(max_length=50)
    categorias=models.ForeignKey(CategoriaCur, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to="estudiante", null=True, blank=True)
    precio=models.FloatField()
    disponibilidad=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name="Curso"
        verbose_name_plural="Cursos"        

estudiante/views.py
from django.shortcuts import render


from .models import Curso

# Create your views here.

def estudiante(request):



    cursos=Curso.objects.all()

    return render(request, "estudiante/estudiante.html", {"cursos":cursos})

estudiante/templates/estudiante/estudiante.html
{% extends "ProyectoWebApp/base.html" %}

{% load static %}



{% block content %}

<div style="color: white; text-align: right; margin-right: 100px;">

    {% if user.is_authenticated %}
    
    Hola {{ user.username }} &nbsp; &nbsp; <a href="{% url 'cerrar_session' %}" style="color: white;">Cerrar sesion</a>
    
    {% else %}
    
    <a href="{% url 'logear'%}" style="color: white;">Login</a> &nbsp; &nbsp; <a href="{% url 'Registrarse' %}" style="color: white;">Registrate</a> 
    
    {% endif %}
    
    </div>
    

<div class="container">

    <div style="float:right;">
    
        <p style="color: white;"></p>

        {% if request.user.is_authenticated %}

            {% include "asignaciondecursos/widget.html" %}

        {% else %}

            <div class="alert alert-danger text-center">Login para asisgnarse</div>

        {% endif %}

    </div>


  <div class="row">

{% for curso in cursos %}

    

    <div class="col-md-3">

        <div class="card" style="width: 100%; margin: 50px 10px;">

        <img src="{{curso.imagen.url}}" class="card-img-top">

        <div class="card-body" style="text-align: center;">

            <h7 class="card-tittle">{{curso.nombre}}</h7>

            <p class="card-text">{{curso.precio}}&nbsp;Q</p>

        </div>

        <div class="card-footer text-center">

            <a href="{% url 'asignaciondecursos:agregar' curso.id %}" class="btn btn-success">Agregar Curso</a>
            

        </div>

        </div>
    </div>

{% endfor %}

  </div>
</div>
{% endblock %}