ProyectoWeb/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls, name='Admin'),

    path('conocenos/', include('conocenos.urls')),

    path('blog/', include('blog.urls')),

    path('contacto/', include('contacto.urls')),

    path('estudiante/', include('estudiante.urls')),

    path('registrarse/', include('registrarse.urls')),

    path('asignaciondecursos/', include('asignaciondecursos.urls')),

    path('asignacion/', include('asignacion.urls')),

    path('docente/', include('docente.urls')),

    path('administrativo/', include('administrativo.urls')),
    
    path('', include('ProyectoWebApp.urls')),

    
    
]

asignaciondecursos/urls.py
from django.urls import path

from .import views 

app_name="asignaciondecursos"

urlpatterns = [
    
    path("agregar/<int:curso_id>/", views.agregar_curso, name="agregar"),
    path("eliminar/<int:curso_id>/", views.eliminar_curso, name="eliminar"),
    path("restar/<int:curso_id>/", views.restar_curso, name="restar"),
    path("limpiar/", views.limpiar_asignaciondecursos, name="limpiar"),
    
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('',views.blog, name='Blog'),
    path('categoria/<int:categoria_id>/', views.categoria, name="categoria")
]

estudiante/urls.py
from django.urls import path

from .import views 

urlpatterns = [
    
    path('',views.estudiante, name='Estudiante'),
    

    
]

asignaciondecursos/models.py
from django.db import models

# Create your models here.

estudiante/models.py
from django.db import models

# Create your models here.

class CategoriaCur(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name="categoriaCur"
        verbose_name_plural="categoriasCur"

    def __str__(self):
        return self.nombre
    

class Curso(models.Model):
    nombre=models.CharField(max_length=50)
    categorias=models.ForeignKey(CategoriaCur, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to="estudiante", null=True, blank=True)
    precio=models.FloatField()
    disponibilidad=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name="Curso"
        verbose_name_plural="Cursos"        

asignaciondecursos/views.py
from django.shortcuts import render

from .asignaciondecursos import Asignaciondecursos

from estudiante.models import Curso

from django.shortcuts import redirect

# Create your views here.

def agregar_curso(request, curso_id):

    asignaciondecursos=Asignaciondecursos(request)

    curso=Curso.objects.get(id=curso_id)

    asignaciondecursos.agregar(curso=curso)

    return redirect("Estudiante")

def eliminar_curso(request, curso_id):

    asignaciondecursos=Asignaciondecursos(request)

    curso=Curso.objects.get(id=curso_id)

    asignaciondecursos.eliminar(curso=curso)

    return redirect("Estudiante")


def restar_curso(request, curso_id):

    asignaciondecursos=Asignaciondecursos(request)

    curso=Curso.objects.get(id=curso_id)

    asignaciondecursos.restar_curso(curso=curso)

    return redirect("Estudiante")


def limpiar_asignaciondecursos(request, curso_id):

    asignaciondecursos=Asignaciondecursos(request)

    asignaciondecursos.limpiar_asignaciondecursos()

    return redirect("Estudiante")

estudiante/views.py
from django.shortcuts import render


from .models import Curso

# Create your views here.

def estudiante(request):



    cursos=Curso.objects.all()

    return render(request, "estudiante/estudiante.html", {"cursos":cursos})

estudiante/templates/asignaciondecursos/widget.html
<table class="table table-bordered" style="color: white;">

    <thead>

        <tr>

            <th colspan="3" class="text-center">

                Asignacion de cursos 

            </th> 

        </tr>

        <tr>

            <th>Curso</th>
            <th>Asignacion</th>
            <th>Quitar Curso</th>


        </tr>

    </thead>

    <tbody>

        {% if request.session.asignaciondecursos.items %}
            {% for key, value in request.session.asignaciondecursos.items %}

                <tr class="text-center">

                    <td>{{value.nombre}}</td>
                    <td>{{value.asignacion}}</td>
                    <td>

                        
                        <a href="{% url 'asignaciondecursos:restar' value.curso_id %}" class="btn btn-sm btn-success">-</a><br/>

                        {{value.precio}}  Q

                    </td>

                </tr>

            {% endfor %}
        {% else %}

            <tr>

                <td colspan="3">

                    <div class="alert alert-danger text-center">

                        Sin cursos asignados

                    </div>

                </td>

            </tr>

        {% endif %}

    </tbody>

    <tfoot>

        <tr>

            <td colspan="3">

                Total: {{importe_total_asignaciondecursos}}  Q

            </td>

        </tr>
        {% if request.session.asignaciondecursos.items %}
        <tr>

            <td colspan="3" style="text-align: center;">
            
                <a href="../asignacion" class="btn btn-success">Asignar cursos seleccionados</a>
            
            </td>

        </tr>
        {% endif %}
    </tfoot>

</table>